#!/usr/bin/env bash

API="https://api.github.com/repos/estesp/manifest-tool/tags"
URL="https://github.com/estesp/manifest-tool/releases/download"
TAG=$(curl -Ls $API | awk -F'"' '/name.*v[0-9]/ {print $4; exit}')
curl -LSo manifest-tool "${URL}/${TAG}/manifest-tool-linux-amd64"
chmod +x manifest-tool